services:
  app:
    container_name: recruitment-task-mmame-app
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.4-cli-alpine
        COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
        COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
        RUN apk add --no-cache git unzip \
            && install-php-extensions pdo_mysql zip
        WORKDIR /app
        COPY . .
        RUN composer config --global allow-plugins true && composer install --no-interaction --no-progress
    command: php -S 0.0.0.0:8080 -t public public/index.php
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: service_healthy

###> doctrine/doctrine-bundle ###
  database:
    container_name: recruitment-task-mmame-db
    image: mysql:26.7
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ptest"]
      interval: 5s
      timeout: 5s
      retries: 20
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
